services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  admin:
    image: adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  pgdata:
